
(function(root, $ /* jQuery */) {

// Bundles generated by the server (or on the client if the forms system is running client side)
var registeredBundles = {};

// Create the interface for the client side
if(undefined === root.oForms) {
    root.oForms = {};
}
root.oForms.client = {
    registerBundle: function(id, bundle) {
        registeredBundles[id] = bundle;
    }
};
